### ISSUE TITLE
Circular dependency between Gnome::Gtk3 and Gnome-Gio

### ISSUE THREAD

**Issue by frithnanth** [MARTIMM/gnome-gio#1]
When installing Gnome::Gtk3 there's a dependency which triggers the installation of Gnome::Gio, but one of its test files, t/SimpleAction.t, tries to use Gnome::Gtk3::Main, which is provided by Gnome::Gtk3.

**Comment by MARTIMM** [comment]
That's embarrassing. I did not pay attention to the use of modules in the test files. It was used to test the signal processing and I needed to start up the main loop. Need to find another way then... At first, I will inhibit those tests,  then I'll find another way.

**Comment by MARTIMM** [comment]
just pushed version 0.5.3. Thanks for your help.

**Comment by frithnanth** [comment]
I guess you pushed v0.5.4, since 0.5.3 is the last one I tried.
I see that the Travis-CI build is still failing (just ended its run).

**Comment by MARTIMM** [comment]
I've pushed 0.5.3.1 to update. Btw. the Travis tests did work! please [look here](https://travis-ci.org/github/MARTIMM/gnome-gio). Also, another test is now started...

**Comment by frithnanth** [comment]
Right, since Travis-CI now waits a lot before starting a build, probably I was looking at the build of the previous version, which was still in progress.  
Now the module installs successfully.  
Thank you!
